# docker-compose.test.yml
version: '3.8'

services:
  app-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      db-test:
        condition: service_healthy
    environment:
      - NODE_ENV=test
      - TEST_DB_HOST=db-test
      - TEST_DB_PORT=3306
      - TEST_DB_NAME=teacher_student_test
      - TEST_DB_USER=root
      - TEST_DB_PASSWORD=password
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
      - ./jest.config.js:/app/jest.config.js
      - ./drizzle.config.ts:/app/drizzle.config.ts
      - /app/node_modules

  db-test:
    image: mysql:8.0
    platform: linux/amd64
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=teacher_student_test
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
      interval: 2s
      timeout: 20s
      retries: 10
    command: --default-authentication-plugin=mysql_native_password